apiVersion: apps/v1
kind: Deployment
metadata:
  name: copyright
  labels:
    app: copyright
spec:
  replicas: 1
  selector:
    matchLabels:
      app: copyright
  template:
    metadata:
      labels:
        app: copyright
    spec:
      containers:
        - name: copyright
          image: username/copyright:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5