server:
  port: 8088

---

spring:
  profiles: default
  cloud:
    gateway:
      routes:
        - id: content
          uri: http://localhost:8081
          predicates:
            - Path=/contents/** 
        - id: copyright
          uri: http://localhost:8082
          predicates:
            - Path=/copyrights/** 
        - id: source
          uri: http://localhost:8083
          predicates:
            - Path=/sources/** 
        - id: mypage
          uri: http://localhost:8084
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true


---

spring:
  profiles: docker
  cloud:
    gateway:
      routes:
        - id: content
          uri: http://content:8080
          predicates:
            - Path=/contents/** 
        - id: copyright
          uri: http://copyright:8080
          predicates:
            - Path=/copyrights/** 
        - id: source
          uri: http://source:8080
          predicates:
            - Path=/sources/** 
        - id: mypage
          uri: http://mypage:8080
          predicates:
            - Path= /mypages/**
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

server:
  port: 8080
