apiVersion: apps/v1
kind: Deployment
metadata:
  name: source
  namespace: musicloud
  labels:
    app: source
spec:
  replicas: 1
  selector:
    matchLabels:
      app: source
  template:
    metadata:
      labels:
        app: source
    spec:
      containers:
        - name: source
          image: musicloud.azurecr.io/source:latest
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
          resources:
            limits:
              cpu: 500m
            requests:
              cpu: 200m
